export {default as chocolat} from './chocolat.png'
export {default as beurre} from './beurre.png'
export {default as confiture} from './confiture.png'
export {default as sucre} from './sucre.png'
export {default as cafe} from './cafe.png'
export {default as thé} from './thé.png'
export {default as biscuit} from './biscuit.png'