export {default as Navbar} from "./Navbar/Navbar"
export {default as Header} from "./Header/Header"
export {default as Product} from "./Product/Product"
export {default as About} from "./About/About"
export {default as Contact} from "./Contact/Contact"
export {default as Footer} from "./Footer/Footer"